services:
  # spring-service:
  #   build: .
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - music_page-network
  flask-service:
    build: flask-service
    ports:
      - 5000:5000
    networks:
      - music_page-network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: music_page
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - music_page-network
networks:
  music_page-network: