# Logging configuration
logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  application:
    name: "Music Page"

#    Datasource configuration
#  For PostgreSQL
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/musicpage"
#    username: "spring"
#    password: "1"
#    driver-class-name: org.postgresql.Driver

#  For H2
  datasource:
    url: "jdbc:h2:mem:testDB"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  #    JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
